[project]
name = "analytics"
version = "0.1.0"
description = "Computer Vision & Thermal Analytics Service for Cable Cam"
authors = [{ name = "losion445" }]
requires-python = ">=3.12,<3.13"
dependencies = [
    "opencv-python-headless (>=4.10.0.84,<5.0.0.0)",
    "redis (>=7.4.0,<8.0.0)",
    "numpy (>=1.26.4,<2.0.0)",
    "ultralytics (>=8.3.0,<9.0.0)",
    # Явно ограничиваем torch только CPU версией
    "torch (>=2.0.0,<3.0.0)",
]

# Указываем Poetry искать torch на серверах PyTorch CPU вместо дефолтного PyPI
[[tool.poetry.source]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
priority = "explicit"

[tool.poetry.dependencies]
torch = { version = "*", source = "pytorch-cpu" }

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
