services:
  backend:
    restart: always
    container_name: motor-control-hub-backend
    build:
      context: ./backend
    expose:
      - "8080"

  frontend:
    restart: always
    depends_on:
      - backend
    build:
      context: ./frontend
    ports:
      - "80:80"

  analytics:
    build:
      context: ./analytics
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_started
      mediamtx:
        condition: service_started
    environment:
      - RTSP_URL=rtsp://mediamtx:8554/cam1
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PYTHONUNBUFFERED=1
    ipc: host

  mediamtx:
    image: bluenviron/mediamtx:latest-ffmpeg
    restart: unless-stopped
    ports:
      - "8554:8554" # RTSP (push/pull from scripts)
      - "1935:1935" # RTMP (pust OBS)
      - "8888:8888" # HLS (vudeo in browser with Hls.js)
      - "8889:8889" # WebRTC (stream from browser with delay < 0.5 seconds)
      - "9997:9997" # API mediaserver 

  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
