
services:
  backend:
    restart: always
    container_name: motor-control-hub-backend
    build:
      context: ./backend
    network_mode: "host"
    
  frontend:
    restart: always
    # depends_on:
    #   - backend
    build:
      context: ./frontend
    ports:
      - "80:80"

networks:
  default:
    name: motor-control-hub-net